logo: "/images/logo.png?raw=true" # your photo (or logo) here
title: Ndcharles Nweke # your name (or website title) here
description: # your text below (remove <br> elements if you don't need line breaks)
Data Scientist | Machine Learning Intern | Storyteller <br><br> 
An engineering graduate who is now in data science/ML. An awesome journey so far🙌. My interests are in real-life applications of data science/ML to business to tackle every day problems.<br><br>
Let's Connect:<br>
<a href="https://www.linkedin.com/in/nndcharles">LinkedIn</a> | <a href="https://www.twitter.com/nndcharles">Twitter</a> | <a href="mailto:ndcharles.edu@gmail.com">Email</a><br>
<a href="https://ndcharles.github.io/assets/resume.pdf">View my Resume</a><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
